import {
  TextInput,
  TextArea,
  PhoneInput,
  MultilineAddress,
  DateInput,
  DatePicker,
  DateTimeInput,
  FileUpload,
  NumberInput,
  Checkbox,
  Signature,
  RatingInput,
  RadioGroup,
  CheckboxGroup,
  Dropdown,
  Tags,
  TimeInput,
  RichText,
  SubmitButton,
  ProductList,
  FixedPayment,
  PaymentInput,
  Donation,
  Appointment,
  ImageChoice,
} from './Fields';

export const FIELD_MAP = {
  TEXT_INPUT: TextInput,
  TEXT_AREA: TextArea,
  PHONE_INPUT: PhoneInput,
  MULTILINE_ADDRESS: MultilineAddress,
  DATE_INPUT: DateInput,
  DATE_PICKER: DatePicker,
  DATE_TIME_INPUT: DateTimeInput,
  FILE_UPLOAD: FileUpload,
  NUMBER_INPUT: NumberInput,
  CHECKBOX: Checkbox,
  SIGNATURE: Signature,
  RATING_INPUT: RatingInput,
  RADIO_GROUP: RadioGroup,
  CHECKBOX_GROUP: CheckboxGroup,
  DROPDOWN: Dropdown,
  TAGS: Tags,
  TIME_INPUT: TimeInput,
  TEXT: RichText,
  SUBMIT_BUTTON: SubmitButton,
  PRODUCT_LIST: ProductList,
  FIXED_PAYMENT: FixedPayment,
  PAYMENT_INPUT: PaymentInput,
  DONATION: Donation,
  APPOINTMENT: Appointment,
  IMAGE_CHOICE: ImageChoice,
};
