export const TestIds = {
  itemName: 'item-name',
  itemDescription: 'item-description',
  itemPrice: 'item-price',
  itemImages: 'item-images',
  itemFeatured: 'item-featured',
  itemVariants: 'item-variants',
  itemPriceVariants: 'item-price-variants',
  itemModifierGroups: 'item-modifier-groups',
  sectionName: 'section-name',
  sectionDescription: 'section-description',
  menuName: 'menu-name',
  menuDescription: 'menu-description',
  menusLoading: 'menus-loading',
  menusError: 'menus-error',
  menuSelector: 'menu-selector',
  locationSelector: 'location-selector',
  labelName: 'label-name',
  labelIcon: 'label-icon',
  modifierGroupName: 'modifier-group-name',
  modifierName: 'modifier-name',
  modifierPrice: 'modifier-price',
  variantName: 'variant-name',
  variantPrice: 'variant-price',
} as const;
